"""create card identity tables

Revision ID: e5d34f3256ae
Revises:
Create Date: 2026-08-27 12:45:02.653548

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e5d34f3256ae"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cards",
        sa.Column("oracle_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("mana_cost", sa.String(length=64), nullable=True),
        sa.Column("cmc", sa.Float(), nullable=False),
        sa.Column("type_line", sa.String(length=128), nullable=False),
        sa.Column("oracle_text", sa.Text(), nullable=True),
        sa.Column("colors", sa.String(length=5), nullable=False),
        sa.Column("color_identity", sa.String(length=5), nullable=False),
        sa.Column("power", sa.String(length=8), nullable=True),
        sa.Column("toughness", sa.String(length=8), nullable=True),
        sa.Column("layout", sa.String(length=32), nullable=False),
        sa.Column("keywords", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("oracle_id", name=op.f("pk_cards")),
    )
    op.create_index(op.f("ix_cards_name"), "cards", ["name"], unique=False)
    op.create_table(
        "sets",
        sa.Column("set_code", sa.String(length=8), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("released_at", sa.Date(), nullable=True),
        sa.Column("set_type", sa.String(length=32), nullable=False),
        sa.Column("is_draftable", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("set_code", name=op.f("pk_sets")),
    )
    op.create_table(
        "card_prints",
        sa.Column("scryfall_id", sa.UUID(), nullable=False),
        sa.Column("oracle_id", sa.UUID(), nullable=False),
        sa.Column("set_code", sa.String(length=8), nullable=False),
        sa.Column("collector_number", sa.String(length=16), nullable=False),
        sa.Column("rarity", sa.String(length=16), nullable=False),
        sa.Column("image_normal", sa.String(length=512), nullable=True),
        sa.Column("image_art_crop", sa.String(length=512), nullable=True),
        sa.ForeignKeyConstraint(
            ["oracle_id"],
            ["cards.oracle_id"],
            name=op.f("fk_card_prints_oracle_id_cards"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["set_code"],
            ["sets.set_code"],
            name=op.f("fk_card_prints_set_code_sets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("scryfall_id", name=op.f("pk_card_prints")),
    )
    op.create_index(
        op.f("ix_card_prints_oracle_id"), "card_prints", ["oracle_id"], unique=False
    )
    op.create_index(
        op.f("ix_card_prints_set_code"), "card_prints", ["set_code"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_card_prints_set_code"), table_name="card_prints")
    op.drop_index(op.f("ix_card_prints_oracle_id"), table_name="card_prints")
    op.drop_table("card_prints")
    op.drop_table("sets")
    op.drop_index(op.f("ix_cards_name"), table_name="cards")
    op.drop_table("cards")
    # ### end Alembic commands ###
